spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/BestBuy
     password: 123456789
     username: postgres
  jpa:
    hibernate:
      ddl-auto : create
    showSql : true
  mail:
    host: smtp.gmail.com
    port: 587
    username: johnny25580@gmail.com
    password: auhgnqbceseduzrh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  expiration:
    access-token: 86400000
    refresh-token: 259200000
