spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/BestBuy
     password: 123456789
     username: postgres
  jpa:
    hibernate:
      ddl-auto : update
    showSql : true
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: johnny25580@gmail.com
    password: auhgnqbceseduzrh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  expiration:
    access-token: 86400000
    refresh-token: 259200000
cloudinary:
  cloud_name: dz66pkcg4
  api_key: 188321597371899
  api_secret: QiHoiEANiNfhZU-DHo5X-9qqojg

rsa :
  privateKey : classpath:certs/private.pem
  publicKey: classpath:certs/public.pem